version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run: sudo npm install --global yarn
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
